name: SCSS Compile 

on:
  push:
    branch: [ master ]

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code 
        uses: actions/checkout@v2

      - name: compile scss
        uses: gha-utilities/sass-build@v0.2.6
        with:
          source: css/resume.scss
          destination: css/resume.css
